import Brauny from "./brauny.jpeg";
import Milk from "./milk.jpeg";
import Kitty from "./kitty.jpeg";
import Wave from "./wave.jpeg";
import Warm from "./warm.jpeg";
import Sunny from "./sunny.jpeg";
import Roze from "./roze.jpeg";

export const data =[
  {
    id: 1,
    name:"Brauny",
    color: "dark",
    material: "cotton 55% and 45% acrylic",
    size: "100/89",
    price: "200", 
    filterItem: "light",
    sortItem: "withoutPic",
    image: Brauny,
    description: "I create magic blankets for newborn baby and oldest.Generally I use natural materials, prefer cotton, wool (antialergic), and sometimes I include a little bit viscose etc. to lighten or make the blanket more durable. I make different size and design it allows cover baby immediately after birth and then use it in the interior of the children's room. Absolutly all my blankets are handmade with love. And I hope that you'll get one for your little baby.",
    showMore: "false",
  },
  {
    id: 2,
    name: "Milk",
    material: "cotton 100%",
    color: "light",
    size: "135/85",
    price: "200", 
    filterItem: "light",
    sortItem: "withoutPic",
    image: Milk,
    description: "I create magic blankets for newborn baby and oldest.Generally I use natural materials, prefer cotton, wool (antialergic), and sometimes I include a little bit viscose etc. to lighten or make the blanket more durable. I make different size and design it allows cover baby immediately after birth and then use it in the interior of the children's room. Absolutly all my blankets are handmade with love. And I hope that you'll get one for your little baby.",
    showMore: "false",
  },
  {
    id: 3,
    name: "Kitty",
    material: "wool 55% and 45% polyester,lining 100% cotton",
    color: "dark",
    size: "90/98",
    price: "200", 
    filterItem: "warm",
    sortItem: "withPic", 
    image: Kitty,
    description: "I create magic blankets for newborn baby and oldest.Generally I use natural materials, prefer cotton, wool (antialergic), and sometimes I include a little bit viscose etc. to lighten or make the blanket more durable. I make different size and design it allows cover baby immediately after birth and then use it in the interior of the children's room. Absolutly all my blankets are handmade with love. And I hope that you'll get one for your little baby.",
    showMore: "false",
  },
  {
    id: 4,
    name: "Wave",
    material: "cotton 57%, 40% acrylic and 3% polyester",
    color: "colored",
    size: "108/96",
    price: "200", 
    filterItem: "light",
    sortItem: "withoutPic",
    image: Wave,
    description: "I create magic blankets for newborn baby and oldest.Generally I use natural materials, prefer cotton, wool (antialergic), and sometimes I include a little bit viscose etc. to lighten or make the blanket more durable. I make different size and design it allows cover baby immediately after birth and then use it in the interior of the children's room. Absolutly all my blankets are handmade with love. And I hope that you'll get one for your little baby.",
    showMore: "false",
  },
  {
    id: 5,
    name: "Warm",
    material: "wool 70% and 30% polyamid",
    color: "dark",
    size: "From 0 to 6 mounths old",
    price: "200",
    filterItem: "warm", 
    sortItem: "withoutPic",
    image: Warm,
    description: "I create magic blankets for newborn baby and oldest.Generally I use natural materials, prefer cotton, wool (antialergic), and sometimes I include a little bit viscose etc. to lighten or make the blanket more durable. I make different size and design it allows cover baby immediately after birth and then use it in the interior of the children's room. Absolutly all my blankets are handmade with love. And I hope that you'll get one for your little baby.",
    showMore: "false",
  },
  {
    id: 6,
    name: "Sunny",
    material: "cotton 67% and 33% viscose",
    color: "colored",
    size: "100/80",
    price: "200", 
    filterItem: "light",
    sortItem: "withoutPic",
    image: Sunny,
    description: "I create magic blankets for newborn baby and oldest.Generally I use natural materials, prefer cotton, wool (antialergic), and sometimes I include a little bit viscose etc. to lighten or make the blanket more durable. I make different size and design it allows cover baby immediately after birth and then use it in the interior of the children's room. Absolutly all my blankets are handmade with love. And I hope that you'll get one for your little baby.",
    showMore: "false",
  },
  {
    id: 7,
    name: "Rose",
    material: "wool 49% and 51% acrylic",
    color: "colored",
    size: "112/74",
    price: "200",
    filterItem: "warm", 
    sortItem: "withoutPic",
    image: Roze,
    description: "I create magic blankets for newborn baby and oldest.Generally I use natural materials, prefer cotton, wool (antialergic), and sometimes I include a little bit viscose etc. to lighten or make the blanket more durable. I make different size and design it allows cover baby immediately after birth and then use it in the interior of the children's room. Absolutly all my blankets are handmade with love. And I hope that you'll get one for your little baby.",
    showMore: "false",
  },
]